// packages/frontend/src/pages/Downloading.tsx
import { useState } from "react";
import { useNavigate } from "react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Progress, Select, Pagination } from "antd";
import * as api from "../api";
import type { TaskEntry, TaskStatusGroup } from "../types";

const statusGroupOptions = [
  { label: "全部任务", value: "all" },
  { label: "进行中", value: "active" },
  { label: "排队中", value: "created" },
  { label: "下载中", value: "downloading" },
  { label: "已完成", value: "success" },
  { label: "失败", value: "failed" },
  { label: "已停止", value: "stopped" },
];

const pageSizeOptions = [
  { label: "10", value: 10 },
  { label: "20", value: 20 },
  { label: "50", value: 50 },
];

function statusLabel(status: string): string {
  switch (status) {
    case "downloading":
      return "下载中";
    case "success":
      return "已完成";
    case "failed":
      return "失败";
    case "created":
      return "排队中";
    case "stopped":
      return "已停止";
    default:
      return status;
  }
}

function statusTagClass(status: string): string {
  switch (status) {
    case "downloading":
      return "bg-blue-600";
    case "success":
      return "bg-emerald-600";
    case "failed":
      return "bg-red-600";
    case "created":
      return "bg-amber-600";
    case "stopped":
      return "bg-zinc-500";
    default:
      return "bg-zinc-500";
  }
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / 1024 ** i).toFixed(1)} ${units[i]}`;
}

function isActiveTask(t: TaskEntry): boolean {
  return t.status !== "success" && t.status !== "failed";
}

function summaryStatusLabel(summaryStatus?: string): string {
  switch (summaryStatus) {
    case "pending":
      return "待总结";
    case "analyzing":
      return "总结中";
    case "failed":
      return "总结失败";
    case "completed":
      return "总结完成";
    default:
      return "未总结";
  }
}

function isSummaryRunning(summaryStatus?: string): boolean {
  return summaryStatus === "pending" || summaryStatus === "analyzing";
}

function aiSummaryButtonLabel(task: TaskEntry): string {
  if (isSummaryRunning(task.summaryStatus)) return "AI 总结中";
  if (task.summaryStatus && task.summaryStatus !== "none") {
    return "重新 AI 总结";
  }
  return "立刻 AI 总结";
}

interface TaskRowProps {
  task: TaskEntry;
  onStop: (id: number) => void;
  onResume: (id: number) => void;
  onDelete: (id: number) => void;
  onTriggerSummary: (id: number) => void;
}

function TaskRow({
  task: initial,
  onStop,
  onResume,
  onDelete,
  onTriggerSummary,
}: TaskRowProps) {
  // 非终态任务每 3s 轮询一次详情，终态自动停止
  const { data: task } = useQuery({
    queryKey: ["task", initial.id],
    queryFn: () => api.getTaskById(initial.id),
    initialData: initial,
    refetchInterval: (query) => {
      const t = query.state.data;
      if (!t) return false;
      return isActiveTask(t) ? 3000 : false;
    },
  });

  const canTrigger = task.status === "success" && !isSummaryRunning(task.summaryStatus);

  return (
    <div className="rounded-lg border border-zinc-200 bg-white p-4">
      <div className="flex items-center justify-between gap-4">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 mb-2">
            <span
              className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium text-white ${statusTagClass(task.status)}`}
            >
              {statusLabel(task.status)}
            </span>
            <span className="text-sm text-zinc-800 truncate">
              {task.title || "(无标题)"}
            </span>
          </div>
          {task.outputFile && (
            <div className="mt-2 text-xs text-zinc-500">
              <span className="text-zinc-400">输出文件：</span>
              <code className="break-all text-zinc-600">
                {task.outputFile}
              </code>
            </div>
          )}
          {task.status === "success" && (
            <div className="mt-2 text-xs text-zinc-500">
              <span className="text-zinc-400">AI 总结：</span>
              <span className="text-zinc-700">
                {summaryStatusLabel(task.summaryStatus)}
              </span>
            </div>
          )}
          {task.status === "downloading" && (
            <div className="mt-2">
              <Progress percent={task.progress ?? 0} size="small" />
            </div>
          )}
          {task.status === "success" && task.fileSize ? (
            <div className="text-xs text-zinc-500 mt-1">
              {formatBytes(task.fileSize)}
            </div>
          ) : null}
          {task.status === "failed" && task.errorMessage && (
            <div className="text-xs text-red-600 mt-1">
              {task.errorMessage}
            </div>
          )}
        </div>
        <div className="flex shrink-0 items-center gap-2">
          {task.status === "created" && (
            <button
              type="button"
              className="rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-amber-600 hover:text-amber-500 hover:border-amber-500 transition-colors"
              onClick={() => onStop(task.id)}
            >
              暂停
            </button>
          )}
          {task.status === "stopped" && (
            <button
              type="button"
              className="rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-emerald-600 hover:text-emerald-500 hover:border-emerald-500 transition-colors"
              onClick={() => onResume(task.id)}
            >
              恢复
            </button>
          )}
          {task.status === "downloading" && (
            <button
              type="button"
              className="rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-zinc-600 hover:text-red-600 hover:border-red-400 transition-colors"
              onClick={() => onDelete(task.id)}
            >
              取消
            </button>
          )}
          {task.status === "success" && (
            <button
              type="button"
              className={`rounded-md border border-zinc-300 px-3 py-1.5 text-xs transition-colors ${
                canTrigger
                  ? "text-rose-600 hover:text-rose-500 hover:border-rose-400"
                  : "cursor-not-allowed text-zinc-500"
              }`}
              disabled={!canTrigger}
              onClick={() => onTriggerSummary(task.id)}
            >
              {aiSummaryButtonLabel(task)}
            </button>
          )}
          {task.status !== "downloading" && (
            <button
              type="button"
              className="rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-red-600 hover:border-red-400 hover:text-red-500 transition-colors"
              onClick={() => onDelete(task.id)}
            >
              删除
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

export function Component() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [statusGroup, setStatusGroup] = useState<TaskStatusGroup>("all");
  const [actionError, setActionError] = useState("");
  const [refreshing, setRefreshing] = useState(false);

  const listQuery = useQuery({
    queryKey: ["tasks", page, pageSize, statusGroup],
    queryFn: () => api.getTasks({ page, pageSize, statusGroup }),
  });

  const tasks = listQuery.data?.items ?? [];
  const total = listQuery.data?.total ?? 0;
  const loading = listQuery.isLoading;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const activeCount = tasks.filter(isActiveTask).length;
  const successCount = tasks.filter((t) => t.status === "success").length;
  const failedCount = tasks.filter((t) => t.status === "failed").length;

  function refreshTask(id: number) {
    return queryClient.invalidateQueries({ queryKey: ["task", id] });
  }

  async function handleRefresh() {
    setRefreshing(true);
    try {
      await listQuery.refetch();
    } finally {
      setRefreshing(false);
    }
  }

  async function handleDelete(id: number) {
    setActionError("");
    try {
      await api.deleteTask(id);
      if (tasks.length === 1 && page > 1) {
        setPage(page - 1);
      } else {
        await listQuery.refetch();
      }
    } catch (e: unknown) {
      setActionError(e instanceof Error ? e.message : "删除任务失败");
    }
  }

  async function handleStop(id: number) {
    setActionError("");
    try {
      await api.stopTask(id);
      await refreshTask(id);
    } catch (e: unknown) {
      setActionError(e instanceof Error ? e.message : "暂停任务失败");
    }
  }

  async function handleResume(id: number) {
    setActionError("");
    try {
      await api.resumeTask(id);
      await refreshTask(id);
    } catch (e: unknown) {
      setActionError(e instanceof Error ? e.message : "恢复任务失败");
    }
  }

  async function handleTriggerAiSummary(id: number) {
    setActionError("");
    const existing = tasks.find((t) => t.id === id);
    if (!existing || !(existing.status === "success" && !isSummaryRunning(existing.summaryStatus))) {
      return;
    }
    try {
      await api.triggerTaskAiSummary(id);
      await refreshTask(id);
    } catch (e: unknown) {
      setActionError(e instanceof Error ? e.message : "触发 AI 总结失败");
    }
  }

  return (
    <div className="space-y-6">
      {actionError && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">
          {actionError}
        </div>
      )}

      <div className="grid grid-cols-3 gap-4">
        <div className="rounded-lg border border-zinc-200 bg-white p-4 text-center">
          <div className="text-2xl font-bold text-blue-600">{activeCount}</div>
          <div className="text-sm text-zinc-500 mt-1">进行中</div>
        </div>
        <div className="rounded-lg border border-zinc-200 bg-white p-4 text-center">
          <div className="text-2xl font-bold text-emerald-600">
            {successCount}
          </div>
          <div className="text-sm text-zinc-500 mt-1">已完成</div>
        </div>
        <div className="rounded-lg border border-zinc-200 bg-white p-4 text-center">
          <div className="text-2xl font-bold text-red-600">{failedCount}</div>
          <div className="text-sm text-zinc-500 mt-1">失败</div>
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <Select
          value={statusGroup}
          options={statusGroupOptions}
          onChange={(v) => {
            setStatusGroup(v);
            setPage(1);
          }}
          style={{ width: 140 }}
        />
        <Button
          loading={refreshing}
          disabled={refreshing}
          onClick={() => void handleRefresh()}
        >
          {refreshing ? "刷新中..." : "刷新当前页"}
        </Button>
        <div className="ml-auto flex items-center gap-2 text-sm text-zinc-500">
          <span>每页</span>
          <Select
            value={pageSize}
            options={pageSizeOptions}
            onChange={(v) => {
              setPageSize(v);
              setPage(1);
            }}
            style={{ width: 80 }}
          />
          <span>条，共 {total} 条</span>
        </div>
      </div>

      {!loading && tasks.length === 0 && (
        <div className="rounded-lg border border-zinc-200 bg-white p-12 text-center">
          <p className="text-zinc-500 mb-4">暂无下载任务</p>
          <Button type="primary" onClick={() => navigate("/")}>
            去添加任务
          </Button>
        </div>
      )}

      {tasks.length > 0 && (
        <div className="space-y-3">
          {tasks.map((task) => (
            <TaskRow
              key={task.id}
              task={task}
              onStop={(id) => void handleStop(id)}
              onResume={(id) => void handleResume(id)}
              onDelete={(id) => void handleDelete(id)}
              onTriggerSummary={(id) => void handleTriggerAiSummary(id)}
            />
          ))}

          <div className="flex items-center justify-between rounded-lg border border-zinc-200 bg-white px-4 py-3">
            <span className="text-sm text-zinc-600">
              第 {page} / {totalPages} 页
            </span>
            <Pagination
              current={page}
              pageSize={pageSize}
              total={total}
              onChange={(nextPage, nextSize) => {
                if (nextSize !== pageSize) {
                  setPageSize(nextSize);
                  setPage(1);
                } else {
                  setPage(nextPage);
                }
              }}
            />
          </div>
        </div>
      )}
    </div>
  );
}

// packages/frontend/src/views/Downloading.vue
<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from "vue";
import { useRouter } from "vue-router";
import type { TaskEntry, TaskStatusGroup } from "../types";
import ProgressBar from "primevue/progressbar";
import * as api from "../api";

const router = useRouter();
const actionError = ref("");
const loading = ref(true);
const refreshing = ref(false);
const tasks = ref<TaskEntry[]>([]);
const page = ref(1);
const pageSize = ref(10);
const total = ref(0);
const hasMore = ref(false);
const statusGroup = ref<TaskStatusGroup>("all");

// 每个活跃任务独立的轮询 timer
const pollTimers = new Map<number, ReturnType<typeof setInterval>>();

const activeTasks = computed(() =>
  tasks.value.filter(
    (t): boolean => t.status !== "success" && t.status !== "failed",
  ),
);

const successCount = computed(
  () => tasks.value.filter((t) => t.status === "success").length,
);

const failedCount = computed(
  () => tasks.value.filter((t) => t.status === "failed").length,
);

const totalPages = computed(() =>
  Math.max(1, Math.ceil(total.value / pageSize.value)),
);

onMounted(() => {
  void loadTasks();
});

onUnmounted(() => {
  stopAllPolls();
});

// ==================== 数据与轮询 ====================

function stopAllPolls() {
  pollTimers.forEach((timer) => clearInterval(timer));
  pollTimers.clear();
}

function syncCurrentPagePolls() {
  stopAllPolls();
  for (const task of tasks.value) {
    if (task.status === "success" || task.status === "failed") {
      continue;
    }
    pollTimers.set(
      task.id,
      setInterval(() => {
        void refreshTask(task.id);
      }, 3000),
    );
  }
}

async function loadTasks() {
  loading.value = true;
  actionError.value = "";
  try {
    const result = await api.getTasks({
      page: page.value,
      pageSize: pageSize.value,
      statusGroup: statusGroup.value,
    });
    tasks.value = result.items;
    total.value = result.total;
    hasMore.value = result.hasMore;
    syncCurrentPagePolls();
  } catch (e: unknown) {
    actionError.value = e instanceof Error ? e.message : "加载任务列表失败";
    tasks.value = [];
    total.value = 0;
    hasMore.value = false;
    stopAllPolls();
  } finally {
    loading.value = false;
    refreshing.value = false;
  }
}

async function refreshTask(id: number) {
  try {
    const task = await api.getTaskById(id);
    const index = tasks.value.findIndex((item) => item.id === id);
    if (index === -1) {
      const timer = pollTimers.get(id);
      if (timer) {
        clearInterval(timer);
        pollTimers.delete(id);
      }
      return;
    }
    tasks.value[index] = task;
    if (task.status === "success" || task.status === "failed") {
      const timer = pollTimers.get(id);
      if (timer) {
        clearInterval(timer);
        pollTimers.delete(id);
      }
    }
  } catch {
    const timer = pollTimers.get(id);
    if (timer) {
      clearInterval(timer);
      pollTimers.delete(id);
    }
  }
}

function summaryStatusLabel(summaryStatus?: string): string {
  switch (summaryStatus) {
    case "pending":
      return "待总结";
    case "analyzing":
      return "总结中";
    case "failed":
      return "总结失败";
    case "completed":
      return "总结完成";
    default:
      return "未总结";
  }
}

function isSummaryRunning(summaryStatus?: string): boolean {
  return summaryStatus === "pending" || summaryStatus === "analyzing";
}

function canTriggerAiSummary(task: TaskEntry): boolean {
  return task.status === "success" && !isSummaryRunning(task.summaryStatus);
}

function aiSummaryButtonLabel(task: TaskEntry): string {
  if (isSummaryRunning(task.summaryStatus)) {
    return "AI 总结中";
  }
  if (task.summaryStatus && task.summaryStatus !== "none") {
    return "重新 AI 总结";
  }
  return "立刻 AI 总结";
}

async function handleTriggerAiSummary(id: number) {
  actionError.value = "";
  const existing = tasks.value.find((task) => task.id === id);
  if (!existing || !canTriggerAiSummary(existing)) {
    return;
  }

  try {
    await api.triggerTaskAiSummary(id);
    const index = tasks.value.findIndex((task) => task.id === id);
    if (index !== -1) {
      tasks.value[index] = {
        ...existing,
        summaryStatus: "pending",
      };
    }
    await refreshTask(id);
  } catch (e: unknown) {
    actionError.value = e instanceof Error ? e.message : "触发 AI 总结失败";
  }
}

// ==================== 操作 ====================

async function handleDelete(id: number) {
  await api.deleteTask(id);
  const timer = pollTimers.get(id);
  if (timer) {
    clearInterval(timer);
    pollTimers.delete(id);
  }
  if (tasks.value.length === 1 && page.value > 1) {
    page.value -= 1;
  }
  await loadTasks();
}

async function handleStop(id: number) {
  await api.stopTask(id);
  await refreshTask(id);
}

async function handleResume(id: number) {
  await api.resumeTask(id);
  await refreshTask(id);
}

async function handleRefresh() {
  refreshing.value = true;
  await loadTasks();
}

async function handleStatusGroupChange(next: TaskStatusGroup) {
  if (statusGroup.value === next) {
    return;
  }
  statusGroup.value = next;
  page.value = 1;
  await loadTasks();
}

async function handlePageChange(nextPage: number) {
  if (nextPage < 1 || nextPage > totalPages.value || nextPage === page.value) {
    return;
  }
  page.value = nextPage;
  await loadTasks();
}

async function handlePageSizeChange(nextSize: number) {
  if (nextSize === pageSize.value) {
    return;
  }
  pageSize.value = nextSize;
  page.value = 1;
  await loadTasks();
}

// ==================== 展示 ====================

function statusLabel(status: string): string {
  switch (status) {
    case "downloading": return "下载中";
    case "success": return "已完成";
    case "failed": return "失败";
    case "created": return "排队中";
    case "stopped": return "已停止";
    default: return status;
  }
}

function statusClass(status: string): string {
  switch (status) {
    case "downloading": return "bg-blue-600";
    case "success": return "bg-emerald-600";
    case "failed": return "bg-red-600";
    case "created": return "bg-amber-600";
    case "stopped": return "bg-zinc-500";
    default: return "bg-zinc-500";
  }
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / 1024 ** i).toFixed(1)} ${units[i]}`;
}
</script>

<template>
  <div class="space-y-6">
    <div v-if="actionError" class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">
      {{ actionError }}
    </div>

    <!-- 统计 -->
    <div class="grid grid-cols-3 gap-4">
      <div class="rounded-lg border border-zinc-200 bg-white p-4 text-center">
        <div class="text-2xl font-bold text-blue-600">{{ activeTasks.length }}</div>
        <div class="text-sm text-zinc-500 mt-1">进行中</div>
      </div>
      <div class="rounded-lg border border-zinc-200 bg-white p-4 text-center">
        <div class="text-2xl font-bold text-emerald-600">{{ successCount }}</div>
        <div class="text-sm text-zinc-500 mt-1">已完成</div>
      </div>
      <div class="rounded-lg border border-zinc-200 bg-white p-4 text-center">
        <div class="text-2xl font-bold text-red-600">{{ failedCount }}</div>
        <div class="text-sm text-zinc-500 mt-1">失败</div>
      </div>
    </div>

    <!-- 工具栏 -->
    <div class="flex flex-wrap items-center gap-2">
      <select
        class="rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-800"
        :value="statusGroup"
        @change="handleStatusGroupChange(($event.target as HTMLSelectElement).value as TaskStatusGroup)"
      >
        <option value="all">全部任务</option>
        <option value="active">进行中</option>
        <option value="created">排队中</option>
        <option value="downloading">下载中</option>
        <option value="success">已完成</option>
        <option value="failed">失败</option>
        <option value="stopped">已停止</option>
      </select>
      <button
        class="rounded-md border border-zinc-300 bg-white px-4 py-2 text-sm text-zinc-800 hover:bg-zinc-100 transition-colors disabled:cursor-not-allowed disabled:text-zinc-500"
        :disabled="refreshing"
        @click="handleRefresh"
      >
        {{ refreshing ? "刷新中..." : "刷新当前页" }}
      </button>
      <div class="ml-auto flex items-center gap-2 text-sm text-zinc-500">
        <span>每页</span>
        <select
          class="rounded-md border border-zinc-300 bg-white px-2 py-1 text-sm text-zinc-800"
          :value="pageSize"
          @change="handlePageSizeChange(Number(($event.target as HTMLSelectElement).value))"
        >
          <option :value="10">10</option>
          <option :value="20">20</option>
          <option :value="50">50</option>
        </select>
        <span>条，共 {{ total }} 条</span>
      </div>
    </div>

    <!-- 空状态 -->
    <div v-if="!loading && tasks.length === 0" class="rounded-lg border border-zinc-200 bg-white p-12 text-center">
      <p class="text-zinc-500 mb-4">暂无下载任务</p>
      <button
        class="rounded-md bg-rose-600 px-4 py-2 text-sm text-white hover:bg-rose-500 transition-colors"
        @click="router.push('/')"
      >
        去添加任务
      </button>
    </div>

    <!-- 任务列表 -->
    <div class="space-y-3" v-if="tasks.length > 0">
      <div
        v-for="task in tasks"
        :key="task.id"
        class="rounded-lg border border-zinc-200 bg-white p-4"
      >
        <div class="flex items-center justify-between gap-4">
          <div class="min-w-0 flex-1">
            <div class="flex items-center gap-2 mb-2">
              <span
                class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium text-white"
                :class="statusClass(task.status)"
              >
                {{ statusLabel(task.status) }}
              </span>
              <span class="text-sm text-zinc-800 truncate">{{ task.title || "(无标题)" }}</span>
            </div>
            <div v-if="task.outputFile" class="mt-2 text-xs text-zinc-500">
              <span class="text-zinc-400">输出文件：</span>
              <code class="break-all text-zinc-600">{{ task.outputFile }}</code>
            </div>
            <div v-if="task.status === 'success'" class="mt-2 text-xs text-zinc-500">
              <span class="text-zinc-400">AI 总结：</span>
              <span class="text-zinc-700">{{ summaryStatusLabel(task.summaryStatus) }}</span>
            </div>
            <div v-if="task.status === 'downloading'" class="mt-2">
              <ProgressBar :value="task.progress ?? 0" />
            </div>
            <div v-if="task.status === 'success' && task.fileSize" class="text-xs text-zinc-500 mt-1">
              {{ formatBytes(task.fileSize) }}
            </div>
            <div v-if="task.status === 'failed' && task.errorMessage" class="text-xs text-red-600 mt-1">
              {{ task.errorMessage }}
            </div>
          </div>
          <!-- Created → 暂停 -->
          <button
            v-if="task.status === 'created'"
            class="shrink-0 rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-amber-600 hover:text-amber-500 hover:border-amber-500 transition-colors"
            @click="handleStop(task.id)"
          >
            暂停
          </button>
          <!-- Stopped → 恢复 -->
          <button
            v-if="task.status === 'stopped'"
            class="shrink-0 rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-emerald-600 hover:text-emerald-500 hover:border-emerald-500 transition-colors"
            @click="handleResume(task.id)"
          >
            恢复
          </button>
          <!-- Downloading → 取消 -->
          <button
            v-if="task.status === 'downloading'"
            class="shrink-0 rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-zinc-600 hover:text-red-600 hover:border-red-400 transition-colors"
            @click="handleDelete(task.id)"
          >
            取消
          </button>
          <button
            v-if="task.status === 'success'"
            class="shrink-0 rounded-md border border-zinc-300 px-3 py-1.5 text-xs transition-colors"
            :class="canTriggerAiSummary(task)
              ? 'text-rose-600 hover:text-rose-500 hover:border-rose-400'
              : 'cursor-not-allowed text-zinc-500'"
            :disabled="!canTriggerAiSummary(task)"
            @click="handleTriggerAiSummary(task.id)"
          >
            {{ aiSummaryButtonLabel(task) }}
          </button>
        </div>
      </div>

      <div class="flex items-center justify-between rounded-lg border border-zinc-200 bg-white px-4 py-3 text-sm text-zinc-600">
        <span>第 {{ page }} / {{ totalPages }} 页</span>
        <div class="flex gap-2">
          <button
            class="rounded-md border border-zinc-300 px-3 py-1.5 transition-colors disabled:cursor-not-allowed disabled:text-zinc-300"
            :disabled="page <= 1"
            @click="handlePageChange(page - 1)"
          >
            上一页
          </button>
          <button
            class="rounded-md border border-zinc-300 px-3 py-1.5 transition-colors disabled:cursor-not-allowed disabled:text-zinc-300"
            :disabled="!hasMore"
            @click="handlePageChange(page + 1)"
          >
            下一页
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
