// packages/frontend/src/App.tsx
import { useEffect } from "react";
import { Link, NavLink, Outlet } from "react-router";
import { Avatar, Space } from "antd";
import { useAuthStore } from "./stores/auth";

function imageSrc(url?: string): string {
  if (!url) return "";
  return `/api/video/cover?url=${encodeURIComponent(url)}`;
}

function navLinkClass({ isActive }: { isActive: boolean }): string {
  return `px-3 py-1.5 rounded-md text-sm transition-colors ${
    isActive
      ? "text-rose-600 bg-rose-50"
      : "text-zinc-600 hover:text-zinc-900 hover:bg-zinc-100"
  }`;
}

export default function App() {
  const user = useAuthStore((s) => s.user);
  const checkLogin = useAuthStore((s) => s.checkLogin);

  useEffect(() => {
    void checkLogin();
  }, [checkLogin]);

  return (
    <div className="min-h-screen bg-zinc-50 text-zinc-900">
      <header className="border-b border-zinc-200 bg-white/80 backdrop-blur">
        <div className="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link
            to="/"
            className="text-lg font-bold text-rose-600 hover:text-rose-500 transition-colors"
          >
            Bilibili 下载器
          </Link>
          <nav className="flex items-center gap-3">
            <NavLink to="/downloading" className={navLinkClass}>
              下载队列
            </NavLink>
            <NavLink to="/summary-tasks" className={navLinkClass}>
              AI 总结任务
            </NavLink>
            <NavLink to="/settings" className={navLinkClass}>
              设置
            </NavLink>
            {!user ? (
              <NavLink to="/login" className={navLinkClass}>
                登录
              </NavLink>
            ) : (
              <NavLink to="/login" className="flex items-center gap-2 hover:opacity-80">
                <Avatar
                  size={28}
                  src={imageSrc(user.face)}
                  alt={user.name}
                  className="border border-zinc-200"
                />
                <span className="text-sm text-zinc-600">{user.name}</span>
              </NavLink>
            )}
          </nav>
        </div>
      </header>
      <main className="max-w-5xl mx-auto px-4 py-6">
        <Outlet />
      </main>
    </div>
  );
}

// packages/frontend/src/App.vue
<script setup lang="ts">
import { useRoute } from "vue-router";
import { computed, onMounted } from "vue";
import { useAuthStore } from "./stores/auth";
import { storeToRefs } from "pinia";

const route = useRoute();
const isHome = computed(() => route.name === "home");

const authStore = useAuthStore();
const { user } = storeToRefs(authStore);

function imageSrc(url?: string): string {
  if (!url) return "";
  return `/api/video/cover?url=${encodeURIComponent(url)}`;
}

onMounted(() => {
  authStore.checkLogin();
});
</script>

<template>
  <div class="min-h-screen bg-zinc-50 text-zinc-900">
    <!-- Header -->
    <header class="border-b border-zinc-200 bg-white/80 backdrop-blur">
      <div class="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between">
        <router-link to="/" class="text-lg font-bold text-rose-600 hover:text-rose-500 transition-colors">
          Bilibili 下载器
        </router-link>
        <nav class="flex items-center gap-3">
          <router-link
            to="/downloading"
            class="px-3 py-1.5 rounded-md text-sm text-zinc-600 hover:text-zinc-900 hover:bg-zinc-100 transition-colors"
          >
            下载队列
          </router-link>
          <router-link
            to="/summary-tasks"
            class="px-3 py-1.5 rounded-md text-sm text-zinc-600 hover:text-zinc-900 hover:bg-zinc-100 transition-colors"
          >
            AI 总结任务
          </router-link>
          <router-link
            to="/settings"
            class="px-3 py-1.5 rounded-md text-sm text-zinc-600 hover:text-zinc-900 hover:bg-zinc-100 transition-colors"
          >
            设置
          </router-link>

          <!-- 登录状态 -->
          <router-link
            v-if="!user"
            to="/login"
            class="px-3 py-1.5 rounded-md text-sm text-zinc-600 hover:text-zinc-900 hover:bg-zinc-100 transition-colors"
          >
            登录
          </router-link>
          <div v-else class="flex items-center gap-2">
            <img
              :src="imageSrc(user.face)"
              :alt="user.name"
              class="w-7 h-7 rounded-full object-cover border border-zinc-200"
            />
            <span class="text-sm text-zinc-600">{{ user.name }}</span>
          </div>
        </nav>
      </div>
    </header>

    <!-- Main -->
    <main class="max-w-5xl mx-auto px-4 py-6">
      <router-view />
    </main>
  </div>
</template>
