// packages/frontend/src/views/VideoDetail.vue
<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { useRoute, useRouter } from "vue-router";
import TreeTable from "primevue/treetable";
import Column from "primevue/column";
import Checkbox from "primevue/checkbox";
import Button from "primevue/button";
import Select from "primevue/select";
import Dialog from "primevue/dialog";
import InputText from "primevue/inputtext";
import { useSettingsStore } from "../stores/settings";
import { useDownloadQueueStore } from "../stores/useDownloadQueueStore";
import * as api from "../api";
import type { VideoInfo, VideoPage, UgcSection, UgcEpisode, SubtitleLang } from "../types";

const route = useRoute();
const router = useRouter();
const settingsStore = useSettingsStore();
const queueStore = useDownloadQueueStore();

const loading = ref(true);
const error = ref("");
const videoInfo = ref<VideoInfo | null>(null);

// 当前选中的 section id
const selectedSectionId = ref<number>(0);

interface TreeNode {
  key: string;
  data: {
    type: "episode" | "page";
    episode?: UgcEpisode;
    page?: VideoPage;
    resolved: boolean;
    downloaded: boolean;
    qualityList?: { id: number; name: string; codecList: string[] }[];
    audioQualityList?: string[];
    selectedQuality?: number;
    selectedCodec?: string;
    selectedAudio?: string;
    selectedSubtitleLang: SubtitleLang;
  };
  children?: TreeNode[];
}

const sectionTrees = ref<Map<number, TreeNode[]>>(new Map());
const selectedKeys = ref<Set<string>>(new Set());

function isPageSelected(nodeKey: string): boolean {
  return selectedKeys.value.has(nodeKey);
}

function setPageSelected(nodeKey: string, val: boolean) {
  if (val) selectedKeys.value.add(nodeKey);
  else selectedKeys.value.delete(nodeKey);
  selectedKeys.value = new Set(selectedKeys.value);
}

onMounted(async () => {
  await settingsStore.load();
  const input = (route.query.input as string) || "";
  if (!input) { router.replace("/"); return; }
  try {
    const info = await api.getVideoInfo(input);
    videoInfo.value = info;

    if (info.ugcSeason?.sections) {
      for (const sec of info.ugcSeason.sections) {
        sectionTrees.value.set(sec.id, buildEpisodeTree(sec));
      }
      selectedSectionId.value = info.ugcSeason.sections[0]?.id ?? 0;
    } else {
      const flatSectionId = -1;
      sectionTrees.value.set(flatSectionId, [buildMockVideoNode(info)]);
      selectedSectionId.value = flatSectionId;
    }

    const allBvidCids = collectBvidCids();
    if (allBvidCids.length > 0) {
      const existing = await api.checkTasks(allBvidCids);
      markDownloaded(existing);
    }
  } catch (e: any) {
    error.value = e.message || "获取视频信息失败";
  } finally {
    loading.value = false;
  }
});

function collectBvidCids(): { bvid: string; cid: number }[] {
  const pairs: { bvid: string; cid: number }[] = [];
  sectionTrees.value.forEach((tree) => {
    tree.forEach((node) => {
      (node.children ?? []).forEach((p) => {
        if (p.data.type === "page" && p.data.page) {
          pairs.push({ bvid: videoInfo.value!.bvid, cid: p.data.page.cid });
        }
      });
    });
  });
  return pairs;
}

function markDownloaded(records: { bvid: string; cid: number }[]) {
  sectionTrees.value.forEach((tree) => {
    tree.forEach((node) => {
      (node.children ?? []).forEach((p) => {
        if (p.data.type !== "page" || !p.data.page) return;
        const rec = records.find(
          (r) => r.bvid === videoInfo.value!.bvid && r.cid === p.data.page!.cid,
        );
        if (!rec) return;
        p.data.downloaded = true;
      });
    });
  });
}

function buildEpisodeTree(section: UgcSection): TreeNode[] {
  return section.episodes.map((ep) => ({
    key: `${section.id}-${ep.cid}`,
    data: { type: "episode" as const, episode: ep, resolved: false, downloaded: false, selectedSubtitleLang: "none" as const },
    children: ep.pages.map((p) => ({
      key: `${section.id}-${ep.cid}-${p.cid}`,
      data: { type: "page" as const, page: p, resolved: false, downloaded: false, selectedSubtitleLang: "none" as const },
    })),
  }));
}

function buildMockVideoNode(info: VideoInfo): TreeNode {
  return {
    key: `video-${info.bvid}`,
    data: {
      type: "episode" as const,
      episode: { aid: info.videoInfo.avid, bvid: info.bvid, cid: info.pages[0]?.cid ?? 0, title: info.title, pages: info.pages },
      resolved: false,
      downloaded: false,
      selectedSubtitleLang: "none",
    },
    children: info.pages.map((p) => ({
      key: `video-${info.bvid}-${p.cid}`,
      data: { type: "page" as const, page: p, resolved: false, downloaded: false, selectedSubtitleLang: "none" as const },
    })),
  };
}

const currentTree = computed(() => sectionTrees.value.get(selectedSectionId.value) ?? []);

const currentSectionTitle = computed(() => {
  if (!videoInfo.value?.ugcSeason?.sections) return "";
  return videoInfo.value.ugcSeason.sections.find((s) => s.id === selectedSectionId.value)?.title ?? "";
});

const currentSectionDefaultPath = computed(() => {
  if (!videoInfo.value) return "";
  return videoInfo.value.ugcSeason?.title
    ? `${videoInfo.value.ugcSeason.title}/${currentSectionTitle.value}`
    : videoInfo.value.title;
});

const allSelectedCount = computed(() => selectedKeys.value.size);

function toggleSection() {
  const tree = currentTree.value;
  if (!tree) return;
  const allSel = tree.every((ep) => (ep.children ?? []).every((p) => isPageSelected(p.key)));
  tree.forEach((ep) => {
    (ep.children ?? []).forEach((p) => {
      setPageSelected(p.key, !allSel);
    });
  });
}

function sectionSelectState(): boolean | null {
  const tree = currentTree.value;
  if (!tree || tree.length === 0) return false;
  let allPages = 0, selPages = 0;
  tree.forEach((ep) => {
    (ep.children ?? []).forEach((p) => {
      allPages++;
      if (isPageSelected(p.key)) selPages++;
    });
  });
  if (allPages === 0) return false;
  if (selPages === allPages) return true;
  if (selPages === 0) return false;
  return null;
}

function toggleEpisode(node: TreeNode) {
  const pages = node.children ?? [];
  if (pages.length === 0) return;
  const allSel = pages.every((p) => isPageSelected(p.key));
  pages.forEach((p) => {
    setPageSelected(p.key, !allSel);
  });
}

function episodeSelectState(node: TreeNode): boolean | null {
  const pages = node.children ?? [];
  if (pages.length === 0) return false;
  const allSel = pages.every((p) => isPageSelected(p.key));
  const noneSel = pages.every((p) => !isPageSelected(p.key));
  return allSel ? true : noneSel ? false : null;
}

const parsing = ref(false);

async function parseAllInSection() {
  if (!videoInfo.value) return;
  parsing.value = true;
  try {
    const unresolvedPages: { bvid: string; cid: number }[] = [];
    const tree = currentTree.value;
    tree.forEach((node) => {
      (node.children ?? []).forEach((p) => {
        if (p.data.type === "page" && !p.data.resolved && p.data.page) {
          unresolvedPages.push({ bvid: videoInfo.value!.bvid, cid: p.data.page.cid });
        }
      });
    });
    if (unresolvedPages.length === 0) return;

    const cids = unresolvedPages.map((e) => e.cid);
    const results = await api.parseAllVideos(videoInfo.value.bvid, cids);
    for (const result of results) {
      tree.forEach((node) => {
        (node.children ?? []).forEach((p) => {
          if (p.data.type === "page" && p.data.page?.cid === result.cid) {
            p.data.resolved = true;
            p.data.qualityList = result.videoQualityList;
            p.data.audioQualityList = result.audioQualityList;
            p.data.selectedQuality = result.videoQualityList[0]?.id ?? settingsStore.settings.defaultQuality;
            p.data.selectedCodec = result.videoQualityList[0]?.codecList[0] ?? "AVC";
            p.data.selectedAudio = result.audioQualityList[0] ?? settingsStore.settings.defaultAudioQuality;
            p.data.selectedSubtitleLang = "none";
          }
        });
      });
    }
  } catch (e: any) {
    error.value = e.message || "解析失败";
  } finally {
    parsing.value = false;
  }
}

const showDirDialog = ref(false);
const dirDialogValue = ref("");

function openDirDialog() {
  dirDialogValue.value = currentSectionDefaultPath.value;
  showDirDialog.value = true;
}

function confirmDirDialog() {
  if (!dirDialogValue.value.trim()) return;
  showDirDialog.value = false;
  doAddToQueue(dirDialogValue.value);
}

async function addToQueue() {
  openDirDialog();
}

async function doAddToQueue(outputPath: string) {
  if (!videoInfo.value) return;
  const downloadTasks: Array<Promise<{ id: number; message: string }>> = [];
  const tree = currentTree.value;

  tree.forEach((node) => {
    const episodeTitle = node.data.episode?.title ?? "";
    (node.children ?? []).forEach((p) => {
      if (p.data.type === "page" && isPageSelected(p.key) && p.data.page) {
        const pg = p.data.page;
        const vq = p.data.selectedQuality ?? settingsStore.settings.defaultQuality;
        const codec = p.data.selectedCodec || settingsStore.settings.defaultCodec || undefined;
        const subtitleLang = p.data.selectedSubtitleLang || "none";
        const task = api.createDownload({
          bvid: videoInfo.value!.bvid,
          cid: pg.cid,
          title: episodeTitle + " - P" + pg.page + " " + pg.title,
          quality: vq,
          codec,
          outputPath,
          fileNameTemplate: settingsStore.settings.defaultFileNameTemplate,
          subtitleLang,
        });
        downloadTasks.push(task);
      }
    });
  });

  try {
    const responses = await Promise.all(
      downloadTasks.map((p) => p.catch(() => ({ id: -1, message: "" }))),
    );
    const successArr = responses.filter((r) => r.id !== -1).map((r) => r.id);
    queueStore.addTaskIds(successArr);

    tree.forEach((node) => {
      (node.children ?? []).forEach((p) => {
        if (p.data.type === "page" && isPageSelected(p.key) && p.data.page) {
          p.data.downloaded = true;
          setPageSelected(p.key, false);
        }
      });
    });
  } catch (e: any) {
    error.value = e.message || "加入队列失败";
  }
}

function formatDuration(seconds: number): string {
  if (!seconds || seconds <= 0) return "--";
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

const subtitleOptions = [
  { label: "不下载", value: "none" },
  { label: "中文", value: "zh" },
  { label: "英文", value: "en" },
  { label: "全部字幕", value: "all" },
];
</script>

<template>
  <div class="space-y-6">
    <div v-if="loading" class="flex items-center justify-center py-20 text-zinc-500">正在加载...</div>

    <div v-else-if="error" class="rounded-lg border border-red-200 bg-red-50 p-6">
      <p class="text-red-600">{{ error }}</p>
      <button class="mt-3 text-sm text-zinc-600 hover:text-zinc-900" @click="router.push('/')">返回首页</button>
    </div>

    <template v-else-if="videoInfo">
      <div class="rounded-lg border border-zinc-200 bg-white p-5 flex gap-5">
        <div v-if="videoInfo.videoInfo.coverUrl" class="w-48 h-28 bg-zinc-100 rounded overflow-hidden shrink-0">
          <img :src="'/api/video/cover?url=' + encodeURIComponent(videoInfo.videoInfo.coverUrl)" :alt="videoInfo.title" class="w-full h-full object-cover" />
        </div>
        <div class="min-w-0 flex-1">
          <h2 class="text-lg font-semibold text-zinc-900">{{ videoInfo.title }}</h2>
          <div class="flex flex-wrap gap-3 mt-2 text-sm text-zinc-600">
            <span>UP：{{ videoInfo.videoInfo.upperName }}</span>
            <span>播放：{{ videoInfo.videoInfo.playCount }}</span>
            <span v-if="videoInfo.ugcSeason" class="text-rose-600">合集：{{ videoInfo.ugcSeason.title }}</span>
          </div>
        </div>
      </div>

      <div v-if="videoInfo.ugcSeason?.sections" class="flex flex-wrap gap-2">
        <button
          v-for="sec in videoInfo.ugcSeason.sections"
          :key="sec.id"
          class="px-3 py-1.5 rounded-full text-xs font-medium transition-colors"
          :class="selectedSectionId === sec.id ? 'bg-rose-600 text-white' : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'"
          @click="selectedSectionId = sec.id"
        >
          {{ sec.title }}
        </button>
      </div>

      <div class="rounded-lg border border-zinc-200 bg-white p-4 flex items-center justify-between gap-4 flex-wrap">
        <div class="flex gap-2">
          <Button label="解析当前页所有视频" severity="danger" size="small" :disabled="parsing" :loading="parsing" @click="parseAllInSection" />
          <Button label="加入下载队列" severity="success" size="small" :disabled="allSelectedCount === 0" @click="addToQueue" />
        </div>
        <span class="text-sm text-zinc-500">已选中 {{ allSelectedCount }} 个分P</span>
      </div>

      <div class="rounded-lg border border-zinc-200 bg-white overflow-hidden">
        <div class="flex items-center gap-3 px-4 py-3 border-b border-zinc-200">
          <Checkbox :modelValue="sectionSelectState()" :binary="true" @update:modelValue="toggleSection()" />
          <span class="text-sm font-medium text-zinc-800">{{ currentSectionTitle || '视频分P' }}</span>
          <span class="text-xs text-zinc-500 ml-auto">{{ currentTree.length }} 个视频</span>
        </div>

        <TreeTable :value="currentTree" class="w-full text-sm" tableStyle="min-width: 100%">
          <Column header="选择" class="w-14">
            <template #body="{ node }">
              <Checkbox v-if="node.data.type === 'episode'" :modelValue="episodeSelectState(node)" :binary="true" @update:modelValue="toggleEpisode(node)" />
              <Checkbox v-else-if="node.data.type === 'page'" :modelValue="isPageSelected(node.key)" :binary="true" @update:modelValue="(val: boolean) => setPageSelected(node.key, val)" />
            </template>
          </Column>
          <Column header="名称" :expander="true">
            <template #body="{ node }">
              <span v-if="node.data.type === 'episode'" class="text-zinc-800 font-medium">{{ node.data.episode?.title }}</span>
              <span v-else class="text-zinc-600 pl-4 text-xs">
                P{{ node.data.page?.page }} {{ node.data.page?.title }}
                <span v-if="node.data.downloaded" class="ml-2 text-emerald-600">已下载</span>
              </span>
            </template>
          </Column>
          <Column header="时长" class="w-20">
            <template #body="{ node }">
              <span class="text-zinc-500 text-xs">{{ node.data.type === 'page' ? formatDuration(node.data.page?.duration ?? 0) : '' }}</span>
            </template>
          </Column>
          <Column header="画质" class="w-32">
            <template #body="{ node }">
              <template v-if="node.data.type === 'page'">
                <Select v-if="node.data.qualityList?.length" v-model="node.data.selectedQuality" :options="node.data.qualityList" optionLabel="name" optionValue="id" size="small" class="w-full" />
                <span v-else-if="!node.data.resolved" class="text-xs text-amber-500">待解析</span>
                <span v-else class="text-xs text-zinc-400">-</span>
              </template>
            </template>
          </Column>
          <Column header="编码" class="w-24">
            <template #body="{ node }">
              <template v-if="node.data.type === 'page'">
                <Select v-if="node.data.qualityList?.length" v-model="node.data.selectedCodec" :options="node.data.qualityList?.find((q: any) => q.id === node.data.selectedQuality)?.codecList ?? []" size="small" class="w-full" />
                <span v-else class="text-xs text-zinc-400">-</span>
              </template>
            </template>
          </Column>
          <Column header="字幕" class="w-28">
            <template #body="{ node }">
              <template v-if="node.data.type === 'page'">
                <Select v-if="node.data.resolved" v-model="node.data.selectedSubtitleLang" :options="subtitleOptions" size="small" class="w-full" />
                <span v-else class="text-xs text-amber-500">待解析</span>
              </template>
            </template>
          </Column>
        </TreeTable>
      </div>
    </template>

    <Dialog v-model:visible="showDirDialog" header="确认下载子目录" :modal="true" :closable="true" :style="{ width: '450px' }">
      <div class="flex flex-col gap-3">
        <label class="text-sm text-zinc-600">请确认或修改下载根目录下的相对子目录：</label>
        <InputText v-model="dirDialogValue" class="w-full" placeholder="例如：合集标题/分区标题" />
        <p class="text-xs text-zinc-500">最终文件会保存到服务端下载根目录下的该子目录中。</p>
        <p v-if="!dirDialogValue.trim()" class="text-xs text-red-600">目录不能为空</p>
      </div>
      <template #footer>
        <Button label="取消" severity="secondary" size="small" @click="showDirDialog = false" />
        <Button label="确认" severity="success" size="small" :disabled="!dirDialogValue.trim()" @click="confirmDirDialog" />
      </template>
    </Dialog>
  </div>
</template>

// packages/frontend/src/pages/VideoDetail.tsx
import { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { useQuery } from "@tanstack/react-query";
import {
  Button,
  Checkbox,
  Input,
  Modal,
  Select,
  Table,
  Typography,
} from "antd";
import type { TableProps } from "antd";
import * as api from "../api";
import { useSettingsStore } from "../stores/settings";
import { useDownloadQueueStore } from "../stores/downloadQueue";
import type {
  SubtitleLang,
  VideoInfo,
  VideoPage,
} from "../types";

interface PageState {
  resolved: boolean;
  downloaded: boolean;
  qualityList?: { id: number; name: string; codecList: string[] }[];
  audioQualityList?: string[];
  selectedQuality?: number;
  selectedCodec?: string;
  selectedAudio?: string;
  selectedSubtitleLang: SubtitleLang;
}

interface EpisodeRow {
  key: string;
  title: string;
  children: PageRow[];
}

interface PageRow {
  key: string;
  cid: number;
  page: VideoPage;
}

type RowData = EpisodeRow | PageRow;

const subtitleOptions = [
  { label: "不下载", value: "none" },
  { label: "中文", value: "zh" },
  { label: "英文", value: "en" },
  { label: "全部字幕", value: "all" },
];

function defaultPageState(): PageState {
  return { resolved: false, downloaded: false, selectedSubtitleLang: "none" };
}

function formatDuration(seconds: number): string {
  if (!seconds || seconds <= 0) return "--";
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export function Component() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const input = (searchParams.get("input") ?? "").trim();
  const settings = useSettingsStore((s) => s.settings);
  const addTaskIds = useDownloadQueueStore((s) => s.addTaskIds);

  const { data: videoInfo, isLoading, isError, error } = useQuery({
    queryKey: ["video-info", input],
    queryFn: () => api.getVideoInfo(input),
    enabled: input.length > 0,
    retry: false,
  });

  const [selectedSectionId, setSelectedSectionId] = useState(0);
  const [pageStates, setPageStates] = useState<Record<string, PageState>>({});
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(new Set());
  const [parsing, setParsing] = useState(false);
  const [dirOpen, setDirOpen] = useState(false);
  const [dirValue, setDirValue] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  function patchPageState(key: string, patch: Partial<PageState>) {
    setPageStates((prev) => ({
      ...prev,
      [key]: { ...defaultPageState(), ...prev[key], ...patch },
    }));
  }

  // 默认选中第一个 section；非合集模式用 -1 表示平铺
  useEffect(() => {
    if (!videoInfo) return;
    const sections = videoInfo.ugcSeason?.sections;
    if (sections && sections.length > 0) {
      setSelectedSectionId((prev) =>
        sections.some((s) => s.id === prev) ? prev : sections[0].id,
      );
    } else {
      setSelectedSectionId(-1);
    }
  }, [videoInfo]);

  // 初始下载态：checkTasks 入队去重
  useEffect(() => {
    if (!videoInfo) return;
    const entries: { key: string; cid: number }[] = [];
    if (videoInfo.ugcSeason?.sections) {
      for (const sec of videoInfo.ugcSeason.sections) {
        for (const ep of sec.episodes) {
          for (const p of ep.pages) {
            entries.push({ key: `${sec.id}-${ep.cid}-${p.cid}`, cid: p.cid });
          }
        }
      }
    } else {
      for (const p of videoInfo.pages) {
        entries.push({ key: `video-${videoInfo.bvid}-${p.cid}`, cid: p.cid });
      }
    }
    if (entries.length === 0) return;
    void api
      .checkTasks(
        entries.map((e) => ({ bvid: videoInfo.bvid, cid: e.cid })),
      )
      .then((records) => {
        const downloaded = new Set(
          records.map((r) => `${r.bvid}-${r.cid}`),
        );
        const patches: Record<string, Partial<PageState>> = {};
        entries.forEach((e) => {
          if (downloaded.has(`${videoInfo.bvid}-${e.cid}`)) {
            patches[e.key] = { downloaded: true };
          }
        });
        setPageStates((prev) => {
          const next = { ...prev };
          Object.entries(patches).forEach(([key, p]) => {
            next[key] = { ...defaultPageState(), ...next[key], ...p };
          });
          return next;
        });
      })
      .catch(() => undefined);
  }, [videoInfo]);

  const currentTree = useMemo<EpisodeRow[]>(() => {
    if (!videoInfo) return [];
    if (videoInfo.ugcSeason?.sections) {
      const section = videoInfo.ugcSeason.sections.find(
        (s) => s.id === selectedSectionId,
      );
      return (section?.episodes ?? []).map((ep) => ({
        key: `${selectedSectionId}-${ep.cid}`,
        title: ep.title,
        children: ep.pages.map((p) => ({
          key: `${selectedSectionId}-${ep.cid}-${p.cid}`,
          cid: p.cid,
          page: p,
        })),
      }));
    }
    return [
      {
        key: `video-${videoInfo.bvid}`,
        title: videoInfo.title,
        children: videoInfo.pages.map((p) => ({
          key: `video-${videoInfo.bvid}-${p.cid}`,
          cid: p.cid,
          page: p,
        })),
      },
    ];
  }, [videoInfo, selectedSectionId]);

  const currentSectionTitle = useMemo(() => {
    if (!videoInfo?.ugcSeason?.sections) return "";
    return (
      videoInfo.ugcSeason.sections.find((s) => s.id === selectedSectionId)
        ?.title ?? ""
    );
  }, [videoInfo, selectedSectionId]);

  const currentSectionDefaultPath = useMemo(() => {
    if (!videoInfo) return "";
    return videoInfo.ugcSeason?.title
      ? `${videoInfo.ugcSeason.title}/${currentSectionTitle}`
      : videoInfo.title;
  }, [videoInfo, currentSectionTitle]);

  const allSelectedCount = selectedKeys.size;

  function getPageState(key: string): PageState {
    return pageStates[key] ?? defaultPageState();
  }

  function episodePageKeys(epKey: string): string[] {
    const ep = currentTree.find((e) => e.key === epKey);
    return ep ? ep.children.map((c) => c.key) : [];
  }

  function episodeSelectState(epKey: string): boolean | null {
    const keys = episodePageKeys(epKey);
    if (keys.length === 0) return false;
    const sel = keys.filter((k) => selectedKeys.has(k)).length;
    if (sel === keys.length) return true;
    if (sel === 0) return false;
    return null;
  }

  function toggleEpisode(epKey: string) {
    const keys = episodePageKeys(epKey);
    if (keys.length === 0) return;
    const allSel = keys.every((k) => selectedKeys.has(k));
    setSelectedKeys((prev) => {
      const next = new Set(prev);
      keys.forEach((k) => (allSel ? next.delete(k) : next.add(k)));
      return next;
    });
  }

  function sectionSelectState(): boolean | null {
    let allPages = 0;
    let selPages = 0;
    currentTree.forEach((ep) => {
      ep.children.forEach((p) => {
        allPages++;
        if (selectedKeys.has(p.key)) selPages++;
      });
    });
    if (allPages === 0) return false;
    if (selPages === allPages) return true;
    if (selPages === 0) return false;
    return null;
  }

  function toggleSection() {
    const allSel = sectionSelectState() === true;
    setSelectedKeys((prev) => {
      const next = new Set(prev);
      currentTree.forEach((ep) =>
        ep.children.forEach((p) =>
          allSel ? next.delete(p.key) : next.add(p.key),
        ),
      );
      return next;
    });
  }

  async function handleParseAllInSection() {
    if (!videoInfo) return;
    setParsing(true);
    setErrorMsg("");
    try {
      const unresolved: { key: string; cid: number }[] = [];
      currentTree.forEach((ep) => {
        ep.children.forEach((p) => {
          if (!getPageState(p.key).resolved) {
            unresolved.push({ key: p.key, cid: p.cid });
          }
        });
      });
      if (unresolved.length === 0) return;

      const results = await api.parseAllVideos(
        videoInfo.bvid,
        unresolved.map((u) => u.cid),
      );
      const patches: Record<string, Partial<PageState>> = {};
      results.forEach((result) => {
        const target = unresolved.find((u) => u.cid === result.cid);
        if (!target) return;
        patches[target.key] = {
          resolved: true,
          qualityList: result.videoQualityList,
          audioQualityList: result.audioQualityList,
          selectedQuality:
            result.videoQualityList[0]?.id ?? settings.defaultQuality,
          selectedCodec: result.videoQualityList[0]?.codecList[0] ?? "AVC",
          selectedAudio:
            result.audioQualityList[0] ?? settings.defaultAudioQuality,
          selectedSubtitleLang: "none",
        };
      });
      setPageStates((prev) => {
        const next = { ...prev };
        Object.entries(patches).forEach(([key, p]) => {
          next[key] = { ...defaultPageState(), ...next[key], ...p };
        });
        return next;
      });
    } catch (e: unknown) {
      setErrorMsg(e instanceof Error ? e.message : "解析失败");
    } finally {
      setParsing(false);
    }
  }

  function openDirDialog() {
    setDirValue(currentSectionDefaultPath);
    setDirOpen(true);
  }

  async function doAddToQueue(outputPath: string) {
    if (!videoInfo) return;
    const tasks: Promise<{ id: number; message: string }>[] = [];
    currentTree.forEach((ep) => {
      ep.children.forEach((p) => {
        if (!selectedKeys.has(p.key)) return;
        const st = getPageState(p.key);
        const vq = st.selectedQuality ?? settings.defaultQuality;
        const codec = st.selectedCodec || settings.defaultCodec || undefined;
        const subtitleLang = st.selectedSubtitleLang || "none";
        tasks.push(
          api.createDownload({
            bvid: videoInfo.bvid,
            cid: p.cid,
            title: `${ep.title} - P${p.page.page} ${p.page.title}`,
            quality: vq,
            codec,
            outputPath,
            fileNameTemplate: settings.defaultFileNameTemplate,
            subtitleLang,
          }),
        );
      });
    });

    try {
      const responses = await Promise.all(
        tasks.map((t) => t.catch(() => ({ id: -1, message: "" }))),
      );
      const successIds = responses
        .filter((r) => r.id !== -1)
        .map((r) => r.id);
      addTaskIds(successIds);

      setSelectedKeys((prev) => {
        const next = new Set(prev);
        currentTree.forEach((ep) =>
          ep.children.forEach((p) => next.delete(p.key)),
        );
        return next;
      });
      setPageStates((prev) => {
        const next = { ...prev };
        currentTree.forEach((ep) =>
          ep.children.forEach((p) => {
            if (next[p.key]) {
              next[p.key] = { ...next[p.key], downloaded: true };
            }
          }),
        );
        return next;
      });
    } catch (e: unknown) {
      setErrorMsg(e instanceof Error ? e.message : "加入队列失败");
    }
  }

  const columns: TableProps<RowData>["columns"] = [
    {
      title: "选择",
      width: 70,
      render: (_, record) =>
        "children" in record ? (
          <Checkbox
            checked={episodeSelectState(record.key) === true}
            indeterminate={episodeSelectState(record.key) === null}
            onChange={() => toggleEpisode(record.key)}
          />
        ) : (
          <Checkbox
            checked={selectedKeys.has(record.key)}
            onChange={(e) => {
              setSelectedKeys((prev) => {
                const next = new Set(prev);
                if (e.target.checked) next.add(record.key);
                else next.delete(record.key);
                return next;
              });
            }}
          />
        ),
    },
    {
      title: "名称",
      render: (_, record) =>
        "children" in record ? (
          <span className="text-zinc-800 font-medium">{record.title}</span>
        ) : (
          <span className="text-zinc-600 pl-4 text-xs">
            P{record.page.page} {record.page.title}
            {getPageState(record.key).downloaded && (
              <span className="ml-2 text-emerald-600">已下载</span>
            )}
          </span>
        ),
    },
    {
      title: "时长",
      width: 90,
      render: (_, record) =>
        "children" in record ? (
          <span className="text-zinc-500 text-xs"> </span>
        ) : (
          <span className="text-zinc-500 text-xs">
            {formatDuration(record.page.duration)}
          </span>
        ),
    },
    {
      title: "画质",
      width: 130,
      render: (_, record) => {
        if ("children" in record) return <span className="text-zinc-400 text-xs">-</span>;
        const st = getPageState(record.key);
        if (!st.resolved) {
          return <span className="text-xs text-amber-500">待解析</span>;
        }
        if (!st.qualityList?.length) {
          return <span className="text-xs text-zinc-400">-</span>;
        }
        return (
          <Select
            size="small"
            className="w-full"
            value={st.selectedQuality}
            options={st.qualityList.map((q) => ({
              label: q.name,
              value: q.id,
            }))}
            onChange={(v) => patchPageState(record.key, { selectedQuality: v })}
          />
        );
      },
    },
    {
      title: "编码",
      width: 110,
      render: (_, record) => {
        if ("children" in record) return <span className="text-zinc-400 text-xs">-</span>;
        const st = getPageState(record.key);
        if (!st.qualityList?.length) {
          return <span className="text-xs text-zinc-400">-</span>;
        }
        const codecs =
          st.qualityList.find((q) => q.id === st.selectedQuality)?.codecList ??
          [];
        return (
          <Select
            size="small"
            className="w-full"
            value={st.selectedCodec}
            options={codecs.map((c) => ({ label: c, value: c }))}
            onChange={(v) => patchPageState(record.key, { selectedCodec: v })}
          />
        );
      },
    },
    {
      title: "字幕",
      width: 120,
      render: (_, record) => {
        if ("children" in record) return <span className="text-zinc-400 text-xs">-</span>;
        const st = getPageState(record.key);
        if (!st.resolved) {
          return <span className="text-xs text-amber-500">待解析</span>;
        }
        return (
          <Select
            size="small"
            className="w-full"
            value={st.selectedSubtitleLang}
            options={subtitleOptions}
            onChange={(v) =>
              patchPageState(record.key, {
                selectedSubtitleLang: v as SubtitleLang,
              })
            }
          />
        );
      },
    },
  ];

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20 text-zinc-500">
        正在加载...
      </div>
    );
  }

  if (isError || !videoInfo) {
    return (
      <div className="rounded-lg border border-red-200 bg-red-50 p-6">
        <p className="text-red-600">
          {isError && error instanceof Error
            ? error.message
            : "获取视频信息失败"}
        </p>
        <button
          type="button"
          className="mt-3 text-sm text-zinc-600 hover:text-zinc-900"
          onClick={() => navigate("/")}
        >
          返回首页
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {errorMsg && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">
          {errorMsg}
        </div>
      )}

      <div className="rounded-lg border border-zinc-200 bg-white p-5 flex gap-5">
        {videoInfo.videoInfo.coverUrl && (
          <div className="w-48 h-28 bg-zinc-100 rounded overflow-hidden shrink-0">
            <img
              src={`/api/video/cover?url=${encodeURIComponent(
                videoInfo.videoInfo.coverUrl,
              )}`}
              alt={videoInfo.title}
              className="w-full h-full object-cover"
            />
          </div>
        )}
        <div className="min-w-0 flex-1">
          <Typography.Title level={4} style={{ marginBottom: 8 }}>
            {videoInfo.title}
          </Typography.Title>
          <div className="flex flex-wrap gap-3 text-sm text-zinc-600">
            <span>UP：{videoInfo.videoInfo.upperName}</span>
            <span>播放：{videoInfo.videoInfo.playCount}</span>
            {videoInfo.ugcSeason && (
              <span className="text-rose-600">
                合集：{videoInfo.ugcSeason.title}
              </span>
            )}
          </div>
        </div>
      </div>

      {videoInfo.ugcSeason?.sections && (
        <div className="flex flex-wrap gap-2">
          {videoInfo.ugcSeason.sections.map((sec) => (
            <button
              key={sec.id}
              type="button"
              className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${
                selectedSectionId === sec.id
                  ? "bg-rose-600 text-white"
                  : "bg-zinc-100 text-zinc-600 hover:bg-zinc-200"
              }`}
              onClick={() => setSelectedSectionId(sec.id)}
            >
              {sec.title}
            </button>
          ))}
        </div>
      )}

      <div className="rounded-lg border border-zinc-200 bg-white p-4 flex items-center justify-between gap-4 flex-wrap">
        <div className="flex gap-2">
          <Button
            color="red"
            variant="solid"
            size="small"
            loading={parsing}
            disabled={parsing}
            onClick={() => void handleParseAllInSection()}
          >
            解析当前页所有视频
          </Button>
          <Button
            color="green"
            variant="solid"
            size="small"
            disabled={allSelectedCount === 0}
            onClick={openDirDialog}
          >
            加入下载队列
          </Button>
        </div>
        <span className="text-sm text-zinc-500">
          已选中 {allSelectedCount} 个分P
        </span>
      </div>

      <div className="rounded-lg border border-zinc-200 bg-white overflow-hidden">
        <div className="flex items-center gap-3 px-4 py-3 border-b border-zinc-200">
          <Checkbox
            checked={sectionSelectState() === true}
            indeterminate={sectionSelectState() === null}
            onChange={toggleSection}
          />
          <span className="text-sm font-medium text-zinc-800">
            {currentSectionTitle || "视频分P"}
          </span>
          <span className="text-xs text-zinc-500 ml-auto">
            {currentTree.length} 个视频
          </span>
        </div>
        <Table<RowData>
          rowKey="key"
          size="small"
          pagination={false}
          columns={columns}
          dataSource={currentTree}
          expandable={{ defaultExpandAllRows: true }}
        />
      </div>

      <Modal
        open={dirOpen}
        title="确认下载子目录"
        okText="确认"
        cancelText="取消"
        okButtonProps={{ disabled: !dirValue.trim() }}
        onOk={() => {
          setDirOpen(false);
          void doAddToQueue(dirValue.trim());
        }}
        onCancel={() => setDirOpen(false)}
      >
        <div className="flex flex-col gap-3">
          <label className="text-sm text-zinc-600">
            请确认或修改下载根目录下的相对子目录：
          </label>
          <Input
            value={dirValue}
            onChange={(e) => setDirValue(e.target.value)}
            placeholder="例如：合集标题/分区标题"
          />
          <p className="text-xs text-zinc-500">
            最终文件会保存到服务端下载根目录下的该子目录中。
          </p>
          {!dirValue.trim() && (
            <p className="text-xs text-red-600">目录不能为空</p>
          )}
        </div>
      </Modal>
    </div>
  );
}
